# Usa una imagen base de Python
FROM pytorch/pytorch:2.1.0-cuda12.1-cudnn8-runtime

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos necesarios al contenedor
COPY models /app/models 
COPY src/inference.py /app/inference.py

# Instala las dependencias necesarias
RUN pip install redis

# Comando para ejecutar tu script Python
# El "-u" facilita que los prints de tu código se muestren por pantalla
CMD ["python", "-u", "inference.py"]